spring:
  datasource:
    url: jdbc:mysql://localhost:3306/-
    username: -
    password: -
  jpa:
    hibernate:
      ddl-auto: update
server:
   port: 8080
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 30000000000
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
